# Generated by Django 4.2.1 on 2023-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="index_date_sr2",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="value_sr2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
