# Generated by Django 4.2.1 on 2023-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_management_index_date_sr2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="charge_frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="index_series",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="option_by_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="security_type_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="type_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
