# Generated by Django 4.2.1 on 2023-05-27 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0002_contract_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_area_then_net_area", models.BooleanField(default=False)),
                ("is_vacant_then_vacancy_reason", models.BooleanField(default=False)),
                ("net_area_then_gross_area", models.BooleanField(default=False)),
                ("option_then_date_provided", models.BooleanField(default=False)),
                ("index_then_date", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
