# Generated by Django 4.2.1 on 2023-06-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_rename_rent_security_management_required_amount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
