# Generated by Django 4.2.1 on 2023-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_managementrule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managementrule",
            name="net_area_then_gross_area",
        ),
        migrations.AlterField(
            model_name="management",
            name="lease_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
