# Generated by Django 4.2.1 on 2023-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_management_index_frequency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConverterTranslator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "converted_string",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "convert_type",
                    models.CharField(
                        choices=[
                            ("INT", "INT"),
                            ("STRING", "STRING"),
                            ("DECIMAL", "DECIMAL"),
                            ("BOOLEAN", "BOOLEAN"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "supplied_value",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("translate_to", models.CharField(max_length=250)),
            ],
        ),
    ]
