# Generated by Django 4.2.1 on 2023-05-27 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_alter_managementrule_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementrule",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
