# Generated by Django 4.2.1 on 2023-06-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_convertertranslator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="convertertranslator",
            options={"ordering": ["convert_type"]},
        ),
    ]
