# Generated by Django 4.2.1 on 2023-06-23 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_alter_convertertranslator_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="convertertranslator",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
