# Generated by Django 4.2.1 on 2023-05-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_alter_management_option_to_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="charge_frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="gross_area",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="income_category_discount_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="income_category_others_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="income_category_rent_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="income_category_service_charges_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="index_frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="index_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="net_area",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="next_index_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="notice_term",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="notice_term_frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="option_type_break_purchase_renew",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="option_type_landlord_tenant_mutual",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="term",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="term_frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="management",
            name="value_added_tax_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
