# Generated by Django 4.2.1 on 2023-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_contract_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementrule',
            name='gross_area_then_net_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='managementrule',
            name='index_then_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='managementrule',
            name='is_vacant_then_vacancy_reason',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='managementrule',
            name='option_then_date_provided',
            field=models.BooleanField(default=True),
        ),
    ]
