# Generated by Django 4.2.1 on 2023-05-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_alter_management_charge_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="rent_security",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
