# Generated by Django 4.2.1 on 2023-08-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_managementrule_vacant_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='type_code',
            new_name='option_type_code',
        ),
    ]
