# Generated by Django 4.2.1 on 2023-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rename_type_code_management_option_type_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentSecurityDepositCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
    ]
