# Generated by Django 4.2.1 on 2023-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_rentsecuritydepositcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='rentsecuritydepositcode',
            name='field_name',
            field=models.CharField(blank=True, choices=[('SECURITY_TYPE_CODE', 'SECURITY_TYPE_CODE'), ('OPTION_TYPE_CODE', 'Option_TYPE_CODE'), ('OPTION_BY_CODE', 'OPTION_BY_CODE'), ('TERM_FREQUENCY', 'TERM_FREQUENCY'), ('CHARGE_FREQUENCY', 'CHARGE_FREQUENCY'), ('CURRENCY_CODE', 'CURRENCY_CODE'), ('UNIT_TYPE', 'UNIT_TYPE'), ('INDEX_FREQUENCY', 'INDEX_FREQUENCY'), ('INDEX_SERIES', 'INDEX_SERIES'), ('INDEX_TYPE', 'INDEX_TYPE')], max_length=250, null=True),
        ),
    ]
