items = [['INT', 'Anden frekvens', 0, 'andenfrekvens'], ['INT', 'Andere frequentie', 0, 'anderefrequentie'],
         ['INT', 'Andere Frequenz', 0, 'anderefrequenz'], ['INT', 'Autre fréquence', 0, 'autrefrquence'],
         ['INT', 'Other Frequency', 0, 'otherfrequency'],
         ['INT', 'Gebruikelijke kwartalen', 10, 'gebruikelijkekwartalen'],
         ['INT', 'Quartiers habituels', 10, 'quartiershabituels'],
         ['INT', 'Sædvanlige Kvarter', 10, 'sdvanligekvarter'],
         ['INT', 'Übliche Quartiere', 10, 'blichequartiere'], ['INT', 'Usual Quarters', 10, 'usualquarters'],
         ['INT', 'Modern Quarters', 20, 'modernquarters'], ['INT', 'Moderne Kvarter', 20, 'modernekvarter'],
         ['INT', 'Moderne Viertel', 20, 'moderneviertel'], ['INT', 'Moderne wijken', 20, 'modernewijken'],
         ['INT', 'Quartiers modernes', 20, 'quartiersmodernes'], ['INT', 'Altschottisch', 30, 'altschottisch'],
         ['INT', 'Gammel skotsk', 30, 'gammelskotsk'], ['INT', 'Old Scottish', 30, 'oldscottish'],
         ['INT', 'Oud Schots', 30, 'oudschots'], ['INT', 'Vieux écossais', 30, 'vieuxcossais'],
         ['INT', 'Écossais moderne', 40, 'cossaismoderne'], ['INT', 'Modern Scottish', 40, 'modernscottish'],
         ['INT', 'Moderne Schots', 40, 'moderneschots'], ['INT', 'Moderne skotsk', 40, 'moderneskotsk'],
         ['INT', 'Modernes Schottisch', 40, 'modernesschottisch'], ['INT', 'Andere kwartalen', 50, 'anderekwartalen'],
         ['INT', 'Andere Viertel', 50, 'andereviertel'], ['INT', 'Andre Kvarter', 50, 'andrekvarter'],
         ['INT', 'Autres quartiers', 50, 'autresquartiers'], ['INT', 'Other Quarters', 50, 'otherquarters'],
         ['INT', 'Maandelijks', 60, 'maandelijks'], ['INT', 'Månedlige', 60, 'mnedlige'],
         ['INT', 'Mensuel', 60, 'mensuel'],
         ['INT', 'Monatlich', 60, 'monatlich'], ['INT', 'Monthly', 60, 'monthly'],
         ['INT', 'Hebdomadaire', 70, 'hebdomadaire'],
         ['INT', 'Ugentlig', 70, 'ugentlig'], ['INT', 'Weekly', 70, 'weekly'], ['INT', 'Wekelijks', 70, 'wekelijks'],
         ['INT', 'Wöchentlich', 70, 'wchentlich'], ['INT', 'Annual', 80, 'annual'], ['INT', 'Annuel', 80, 'annuel'],
         ['INT', 'Årligt', 80, 'rligt'], ['INT', 'Jaarlijks', 80, 'jaarlijks'], ['INT', 'Jährlich', 80, 'jhrlich'],
         ['INT', 'Halbjährlich', 90, 'halbjhrlich'], ['INT', 'Half Yearly', 90, 'halfyearly'],
         ['INT', 'Halfjaarlijks', 90, 'halfjaarlijks'], ['INT', 'Halvårligt', 90, 'halvrligt'],
         ['INT', 'Semestriel', 90, 'semestriel'], ['INT', 'Dagelijks', 100, 'dagelijks'],
         ['INT', 'Daglige', 100, 'daglige'],
         ['INT', 'Daily', 100, 'daily'], ['INT', 'Quotidien', 100, 'quotidien'], ['INT', 'Täglich', 100, 'tglich'],
         ['INT', 'Alle zwei Wochen', 110, 'allezweiwochen'], ['INT', 'Bihebdomadaire', 110, 'bihebdomadaire'],
         ['INT', 'Fortnightly', 110, 'fortnightly'], ['INT', 'Hver fjortende dag', 110, 'hverfjortendedag'],
         ['INT', 'Tweewekelijks', 110, 'tweewekelijks'], ['INT', 'Fire Ugentlige', 120, 'fireugentlige'],
         ['INT', 'Four Weekly', 120, 'fourweekly'], ['INT', 'Quatre semaines', 120, 'quatresemaines'],
         ['INT', 'Vier wekelijks', 120, 'vierwekelijks'], ['INT', 'Vierwöchentlich', 120, 'vierwchentlich'],
         ['INT', 'Bimensuel', 130, 'bimensuel'], ['INT', 'Bi-monthly', 130, 'bimonthly'],
         ['INT', 'To-månedligt', 130, 'tomnedligt'], ['INT', 'Tweemaandelijks', 130, 'tweemaandelijks'],
         ['INT', 'Zweimonatlich', 130, 'zweimonatlich'], ['INT', 'Andere', 0, 'andere'], ['INT', 'Andet', 0, 'andet'],
         ['INT', 'Autre', 0, 'autre'], ['INT', 'Other', 0, 'other'],
         ['INT', 'Consumentenprijsindex ', 10, 'consumentenprijsindex'],
         ['INT', 'Consumer Price Index', 10, 'consumerpriceindex'], ['INT', 'CPI', 10, 'cpi'],
         ['INT', 'Forbrugerprisindekset', 10, 'forbrugerprisindekset'], ['INT', 'IPC', 10, 'ipc'],
         ['INT', 'Verbraucherpreisindex', 10, 'verbraucherpreisindex'], ['INT', 'VPI', 10, 'vpi'],
         ['INT', 'Tendance', 20, 'tendance'], ['INT', 'Tendens', 20, 'tendens'], ['INT', 'Trend', 20, 'trend'],
         ['INT', 'Points', 30, 'points'], ['INT', 'Punkte', 30, 'punkte'], ['INT', 'Punten', 30, 'punten'],
         ['INT', 'Accord contractuel', 90, 'accordcontractuel'], ['INT', 'Contract agreement', 90, 'contractagreement'],
         ['INT', 'Contractafspraak', 90, 'contractafspraak'], ['INT', 'Kontraktaftale', 90, 'kontraktaftale'],
         ['INT', 'Vertragsvereinbarung', 90, 'vertragsvereinbarung'], ['INT', 'Abweichend', 99, 'abweichend'],
         ['INT', 'Afwijkend', 99, 'afwijkend'], ['INT', 'Divergent', 99, 'divergent'],
         ['INT', 'Divergerende', 99, 'divergerende'], ['STRING', 'Chronologique', 'Chronological', 'chronologique'],
         ['STRING', 'Chronologisch', 'Chronological', 'chronologisch'],
         ['STRING', 'Fester Rhythmus', 'Chronological', 'festerrhythmus'],
         ['STRING', 'Kronologisk', 'Chronological', 'kronologisk'],
         ['STRING', 'Geografisch', 'Geographically', 'geografisch'],
         ['STRING', 'Geografisk', 'Geographically', 'geografisk'],
         ['STRING', 'Géographiquement', 'Geographically', 'gographiquement'],
         ['STRING', 'Geographisch', 'Geographically', 'geographisch'],
         ['STRING', 'Percentage', 'Percentage', 'percentage'],
         ['STRING', 'pourcentage', 'Percentage', 'pourcentage'], ['STRING', 'procent', 'Percentage', 'procent'],
         ['STRING', 'Prozent', 'Percentage', 'prozent'], ['STRING', 'Prozentsatz', 'Percentage', 'prozentsatz'],
         ['STRING', 'Taksonomisk', 'Taxonomic', 'taksonomisk'], ['STRING', 'Taxonomique', 'Taxonomic', 'taxonomique'],
         ['STRING', 'Taxonomisch', 'Taxonomic', 'taxonomisch'],
         ['STRING', 'Location étape', 'Step rent', 'locationtape'],
         ['STRING', "Chiffre d'affaires loyer", 'Turnover rent', 'chiffredaffairesloyer'],
         ['STRING', 'Trinleje', 'Step rent', 'trinleje'],
         ['STRING', 'Omsætningsleje', 'Turnover rent', 'omstningsleje'],
         ['STRING', 'Stufenmiete', 'Step rent', 'stufenmiete'],
         ['STRING', 'Umsatzmiete', 'Turnover rent', 'umsatzmiete'],
         ['STRING', 'Stapsgewijze huur', 'Step rent', 'stapsgewijzehuur'],
         ['STRING', 'Omzethuur', 'Turnover rent', 'omzethuur'], ['STRING', 'Nee', 0, 'nee'],
         ['STRING', 'Nein', 0, 'nein'],
         ['STRING', 'Njet', 0, 'njet'], ['STRING', 'No', 0, 'no'], ['STRING', 'Da', 1, 'da'], ['STRING', 'Ja', 1, 'ja'],
         ['STRING', 'Qui', 1, 'qui'], ['STRING', 'Yes', 1, 'yes'], ['STRING', 'Landheer', 10, 'landheer'],
         ['STRING', 'Landlord', 10, 'landlord'], ['STRING', 'Udlejer', 10, 'udlejer'],
         ['STRING', 'Vermieter', 10, 'vermieter'],
         ['STRING', 'Huurder', 20, 'huurder'], ['STRING', 'Lejer', 20, 'lejer'], ['STRING', 'Mieter', 20, 'mieter'],
         ['STRING', 'Tenant', 20, 'tenant'], ['STRING', 'Either', 30, 'either'], ['STRING', 'Elke', 30, 'elke'],
         ['STRING', 'Enten', 30, 'enten'], ['STRING', 'Entweder', 30, 'entweder'], ['STRING', 'Begge', 40, 'begge'],
         ['STRING', 'Beide', 40, 'beide'], ['STRING', 'Both', 40, 'both'], ['STRING', 'Break', 10, 'break'],
         ['STRING', 'Brechen', 10, 'brechen'], ['STRING', 'Pause', 10, 'pause'], ['STRING', 'Pauze', 10, 'pauze'],
         ['STRING', 'Aankoop', 20, 'aankoop'], ['STRING', 'Kaufen', 20, 'kaufen'], ['STRING', 'Køb', 20, 'kb'],
         ['STRING', 'Purchase', 20, 'purchase'], ['STRING', 'Erneuern', 30, 'erneuern'],
         ['STRING', 'Forny', 30, 'forny'],
         ['STRING', 'Renew', 30, 'renew'], ['STRING', 'Vernieuwen', 30, 'vernieuwen'],
         ['STRING', 'Almindeligt område', 'Common Area', 'almindeligtomrde'],
         ['STRING', 'Espace commun', 'Common Area', 'espacecommun'],
         ['STRING', 'Gemeenschappelijke ruimte', 'Common Area', 'gemeenschappelijkeruimte'],
         ['STRING', 'Gemeinschaftsraum', 'Common Area', 'gemeinschaftsraum'],
         ['STRING', 'Couloirs', 'Corridors', 'couloirs'],
         ['STRING', 'Gangen', 'Corridors', 'gangen'], ['STRING', 'Korridore', 'Corridors', 'korridore'],
         ['STRING', 'Korridorer', 'Corridors', 'korridorer'], ['STRING', 'Façade', 'Fasade', 'faade'],
         ['STRING', 'Fasade', 'Fasade', 'fasade'], ['STRING', 'Fassade', 'Fasade', 'fassade'],
         ['STRING', 'gevel', 'Fasade', 'gevel'], ['STRING', 'Benzinestation', 'Gas Station', 'benzinestation'],
         ['STRING', 'Station-essence', 'Gas Station', 'stationessence'],
         ['STRING', 'Tankstation', 'Gas Station', 'tankstation'], ['STRING', 'Tankstelle', 'Gas Station', 'tankstelle'],
         ['STRING', 'Bon stockage', 'Good stora', 'bonstockage'],
         ['STRING', 'God opbevaring', 'Good stora', 'godopbevaring'],
         ['STRING', 'Goede opslag', 'Good stora', 'goedeopslag'],
         ['STRING', 'Guter Speicher', 'Good stora', 'guterspeicher'],
         ['STRING', 'Bureau', 'Office', 'bureau'], ['STRING', 'Büro', 'Office', 'bro'],
         ['STRING', 'Kantoor', 'Office', 'kantoor'], ['STRING', 'Kontor', 'Office', 'kontor'],
         ['STRING', 'Ander', 'Other', 'ander'], ['STRING', 'Andere', 'Other', 'andere'],
         ['STRING', 'Andet', 'Other', 'andet'],
         ['STRING', 'Autre', 'Other', 'autre'], ['STRING', 'Außen', 'Outside', 'auen'],
         ['STRING', 'Buiten', 'Outside', 'buiten'], ['STRING', 'Dehors', 'Outside', 'dehors'],
         ['STRING', 'Uden for', 'Outside', 'udenfor'], ['STRING', 'Parken', 'Parking', 'parken'],
         ['STRING', 'Parkeren', 'Parking', 'parkeren'], ['STRING', 'Parkering', 'Parking', 'parkering'],
         ['STRING', 'Parking', 'Parking', 'parking'], ['STRING', 'Détail', 'Retail', 'dtail'],
         ['STRING', 'Detailhandel', 'Retail', 'detailhandel'], ['STRING', 'Einzelhandel', 'Retail', 'einzelhandel'],
         ['STRING', 'Dach', 'Roof', 'dach'], ['STRING', 'Dak', 'Roof', 'dak'], ['STRING', 'Tag', 'Roof', 'tag'],
         ['STRING', 'Toit', 'Roof', 'toit'], ['STRING', 'Sociaal', 'Social', 'sociaal'],
         ['STRING', 'Social', 'Social', 'social'], ['STRING', 'Sozial', 'Social', 'sozial'],
         ['STRING', 'Lagerung', 'Storage', 'lagerung'], ['STRING', 'Opbevaring', 'Storage', 'opbevaring'],
         ['STRING', 'Opslag', 'Storage', 'opslag'], ['STRING', 'Stockage', 'Storage', 'stockage'],
         ['STRING', 'Technique', 'Technical', 'technique'], ['STRING', 'Teknisk', 'Technical', 'teknisk'],
         ['STRING', 'Technisch', 'Technical ', 'technisch'], ['STRING', 'Toiletten', 'Toilets', 'toiletten'],
         ['STRING', 'Toiletter', 'Toilets', 'toiletter'], ['STRING', 'Toilettes', 'Toilets', 'toilettes'],
         ['STRING', 'Couloirs verticaux', 'Vertical Corridors', 'couloirsverticaux'],
         ['STRING', 'Lodrette korridorer', 'Vertical Corridors', 'lodrettekorridorer'],
         ['STRING', 'Verticale gangen', 'Vertical Corridors', 'verticalegangen'],
         ['STRING', 'Vertikale Korridore', 'Vertical Corridors', 'vertikalekorridore'],
         ['STRING', 'Woonhuis', 'Residential', 'woonhuis'], ['STRING', 'Wohnen', 'Residential', 'wohnen'],
         ['STRING', 'Bolig', 'Residential', 'bolig'], ['STRING', 'Résidentiel', 'Residential', 'rsidentiel'],
         ['STRING', 'Appartement', 'Residential', 'appartement'],
         ['STRING', 'Eengezinswoning', 'Residential', 'eengezinswoning'], ['STRING', 'EGW', 'Residential', 'egw'],
         ['STRING', 'MGW', 'Residential', 'mgw'], ['STRING', 'Appartement', 'Residential', 'appartement'],
         ['STRING', 'Maison unifamiliale', 'Residential', 'maisonunifamiliale'],
         ['STRING', 'Lejlighed', 'Residential', 'lejlighed'], ['STRING', 'Enfamiliehus', 'Residential', 'enfamiliehus'],
         ['STRING', 'Wohnung', 'Residential', 'wohnung'],
         ['STRING', 'Einfamilienhaus', 'Residential', 'einfamilienhaus'],
         ['STRING', 'Apartment', 'Residential', 'apartment'],
         ['STRING', 'Single-family house', 'Residential', 'singlefamilyhouse'],
         ['STRING', 'Studio', 'Residential', 'studio'],
         ['STRING', 'Bungalow', 'Residential', 'bungalow'], ['STRING', 'Maisonnette', 'Residential', 'maisonnette'],
         ['BOOLEAN', 'Nee', 0, 'nee'], ['BOOLEAN', 'Nein', 0, 'nein'], ['BOOLEAN', 'Njet', 0, 'njet'],
         ['BOOLEAN', 'No', 0, 'no'], ['BOOLEAN', 'Da', 1, 'da'], ['BOOLEAN', 'Ja', 1, 'ja'],
         ['BOOLEAN', 'Qui', 1, 'qui'],
         ['BOOLEAN', 'Yes', 1, 'yes'], ['STRING', 'Nee', 0, 'nee'], ['STRING', 'Nein', 0, 'nein'],
         ['STRING', 'Njet', 0, 'njet'], ['STRING', 'No', 0, 'no'], ['STRING', 'Da', 1, 'da'], ['STRING', 'Ja', 1, 'ja'],
         ['STRING', 'Qui', 1, 'qui'], ['STRING', 'Yes', 1, 'yes'], ['INT', 'Bank Guarantee', 10, 'bankguarantee'],
         ['INT', 'Company Guarantee', 20, 'companyguarantee'], ['INT', 'Deposit', 30, 'deposit'],
         ['INT', 'None', 40, 'none'],
         ['INT', 'Bankgarantie', 10, 'bankgarantie'], ['INT', 'Bedrijfsgarantie', 20, 'bedrijfsgarantie'],
         ['INT', 'Borg', 30, 'borg'], ['INT', 'Geen', 40, 'geen'], ['INT', 'Bankgarantie', 10, 'bankgarantie'],
         ['INT', 'Firmengarantie', 20, 'firmengarantie'], ['INT', 'Kaution', 30, 'kaution'],
         ['INT', 'Keiner', 40, 'keiner'],
         ['INT', 'Garantie bancaire', 10, 'garantiebancaire'], ['INT', 'Garantie Entreprise', 20, 'garantieentreprise'],
         ['INT', 'Dépôt', 30, 'dpt'], ['INT', 'Aucun', 40, 'aucun'], ['INT', 'Bank garanti', 10, 'bankgaranti'],
         ['INT', 'Virksomhedsgaranti', 20, 'virksomhedsgaranti'], ['INT', 'Depositum', 30, 'depositum'],
         ['INT', 'Ingen', 40, 'ingen']]

import openpyxl
def create_excel():
    # Create a new workbook and select the active sheet
    workbook = openpyxl.Workbook()
    sheet = workbook.active

    # Write the headers

    headers = ['convert_type', 'supplied_value', 'translate_to', ]
    sheet.append(headers)

    # Write the data rows
    for row in items:
        sheet.append(row)

    # Save the workbook
    workbook.save('items.xlsx')
create_excel()