# Generated by Django 4.2.1 on 2023-05-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataStructureRequiredField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lease_id", models.BooleanField(default=True)),
                ("lease_start_date", models.BooleanField(default=True)),
                ("first_day_of_term_date", models.BooleanField(default=True)),
                ("last_day_of_term_date", models.BooleanField(default=False)),
                ("lease_expiration_date", models.BooleanField(default=True)),
                ("rent_security", models.BooleanField(default=False)),
                ("rent_security_type", models.BooleanField(default=False)),
                ("tenant_id", models.BooleanField(default=True)),
                ("tenant_name", models.BooleanField(default=True)),
                ("is_company", models.BooleanField(default=True)),
                ("option_from_date", models.BooleanField(default=False)),
                ("option_to_date", models.BooleanField(default=False)),
                (
                    "option_type_break_purchase_renew",
                    models.BooleanField(default=False),
                ),
                (
                    "option_type_landlord_tenant_mutual",
                    models.BooleanField(default=False),
                ),
                ("term", models.BooleanField(default=False)),
                ("notice_term", models.BooleanField(default=False)),
                ("notice_term_date", models.BooleanField(default=False)),
                ("notice_term_frequency", models.BooleanField(default=False)),
                ("fund_id", models.BooleanField(default=True)),
                ("property_id", models.BooleanField(default=True)),
                ("unit_id", models.BooleanField(default=True)),
                ("unit_type", models.BooleanField(default=True)),
                ("gross_area", models.BooleanField(default=True)),
                ("net_area", models.BooleanField(default=True)),
                ("is_vacant", models.BooleanField(default=True)),
                ("vacancy_reason", models.BooleanField(default=False)),
                ("income_category_rent_amount", models.BooleanField(default=True)),
                (
                    "income_category_service_charges_amount",
                    models.BooleanField(default=False),
                ),
                ("income_category_others_amount", models.BooleanField(default=False)),
                ("income_category_discount_amount", models.BooleanField(default=False)),
                ("term_frequency", models.BooleanField(default=True)),
                ("charge_frequency", models.BooleanField(default=True)),
                ("value_added_tax", models.BooleanField(default=True)),
                ("value_added_tax_rate", models.BooleanField(default=True)),
                ("start_payment_schedule", models.BooleanField(default=True)),
                ("end_payment_schedule", models.BooleanField(default=False)),
                ("currency", models.BooleanField(default=True)),
                ("index_series", models.BooleanField(default=False)),
                ("index_type", models.BooleanField(default=False)),
                ("start_date", models.BooleanField(default=False)),
                ("index_frequency", models.BooleanField(default=False)),
                ("index_date", models.BooleanField(default=False)),
                ("index_value", models.BooleanField(default=False)),
                ("next_index_date", models.BooleanField(default=False)),
                ("next_index_value", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DataStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lease_id",
                    models.CharField(
                        blank=True, default="lease_id ", max_length=250, null=True
                    ),
                ),
                (
                    "lease_start_date",
                    models.CharField(
                        blank=True,
                        default="lease_start_date",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "first_day_of_term_date",
                    models.CharField(
                        blank=True,
                        default="first_day_of_term_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "last_day_of_term_date",
                    models.CharField(
                        blank=True,
                        default="last_day_of_term_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "lease_expiration_date",
                    models.CharField(
                        blank=True,
                        default="lease_expiration_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "rent_security",
                    models.CharField(
                        blank=True, default="rent_security", max_length=250, null=True
                    ),
                ),
                (
                    "rent_security_type",
                    models.CharField(
                        blank=True,
                        default="rent_security_type",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True, default="tenant_id", max_length=250, null=True
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        blank=True, default="tenant_name", max_length=250, null=True
                    ),
                ),
                (
                    "is_company",
                    models.CharField(
                        blank=True, default="is_company", max_length=250, null=True
                    ),
                ),
                (
                    "option_from_date",
                    models.CharField(
                        blank=True,
                        default="option_from_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "option_to_date",
                    models.CharField(
                        blank=True, default="option_to_date", max_length=240, null=True
                    ),
                ),
                (
                    "option_type_break_purchase_renew",
                    models.CharField(
                        blank=True,
                        default="option_type_break_purchase_renew",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "option_type_landlord_tenant_mutual",
                    models.CharField(
                        blank=True,
                        default="option_type_landlord_tenant_mutual",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True, default="term", max_length=250, null=True
                    ),
                ),
                (
                    "notice_term",
                    models.CharField(
                        blank=True, default="notice_term", max_length=250, null=True
                    ),
                ),
                (
                    "notice_term_date",
                    models.CharField(
                        blank=True,
                        default="notice_term_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "notice_term_frequency",
                    models.CharField(
                        blank=True,
                        default="notice_term_frequency",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "fund_id",
                    models.CharField(
                        blank=True, default="fund_id", max_length=250, null=True
                    ),
                ),
                (
                    "property_id",
                    models.CharField(
                        blank=True, default="property_id", max_length=250, null=True
                    ),
                ),
                (
                    "unit_id",
                    models.CharField(
                        blank=True, default="unit_id", max_length=250, null=True
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        blank=True, default="unit_type", max_length=250, null=True
                    ),
                ),
                (
                    "gross_area",
                    models.CharField(
                        blank=True, default="gross_area", max_length=250, null=True
                    ),
                ),
                (
                    "net_area",
                    models.CharField(
                        blank=True, default="net_area", max_length=250, null=True
                    ),
                ),
                (
                    "is_vacant",
                    models.CharField(
                        blank=True, default="is_vacant", max_length=250, null=True
                    ),
                ),
                (
                    "vacancy_reason",
                    models.CharField(
                        blank=True, default="vacancy_reason", max_length=250, null=True
                    ),
                ),
                (
                    "income_category_rent_amount",
                    models.CharField(
                        blank=True,
                        default="income_category_rent_amount",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "income_category_service_charges_amount",
                    models.CharField(
                        blank=True,
                        default="income_category_service_charges_amount",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "income_category_others_amount",
                    models.CharField(
                        blank=True,
                        default="income_category_others_amount",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "income_category_discount_amount",
                    models.CharField(
                        blank=True,
                        default="income_category_discount_amount",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "term_frequency",
                    models.CharField(
                        blank=True, default="term_frequency", max_length=250, null=True
                    ),
                ),
                (
                    "charge_frequency",
                    models.CharField(
                        blank=True,
                        default="charge_frequency",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "value_added_tax",
                    models.CharField(
                        blank=True, default="value_added_tax", max_length=250, null=True
                    ),
                ),
                (
                    "value_added_tax_rate",
                    models.CharField(
                        blank=True,
                        default="value_added_tax_rate",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "start_payment_schedule",
                    models.CharField(
                        blank=True,
                        default="start_payment_schedule",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "end_payment_schedule",
                    models.CharField(
                        blank=True,
                        default="end_payment_schedule",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="currency", max_length=250, null=True
                    ),
                ),
                (
                    "index_series",
                    models.CharField(
                        blank=True, default="index_series", max_length=250, null=True
                    ),
                ),
                (
                    "index_type",
                    models.CharField(
                        blank=True, default="index_type", max_length=250, null=True
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True, default="start_date", max_length=240, null=True
                    ),
                ),
                (
                    "index_frequency",
                    models.CharField(
                        blank=True, default="index_frequency", max_length=250, null=True
                    ),
                ),
                (
                    "index_date",
                    models.CharField(
                        blank=True, default="index_date", max_length=240, null=True
                    ),
                ),
                (
                    "index_value",
                    models.CharField(
                        blank=True, default="index_value", max_length=250, null=True
                    ),
                ),
                (
                    "next_index_date",
                    models.CharField(
                        blank=True, default="next_index_date", max_length=240, null=True
                    ),
                ),
                (
                    "next_index_value",
                    models.CharField(
                        blank=True,
                        default="next_index_value",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_structure",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
