# Generated by Django 4.2.1 on 2023-06-11 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataStructureRequiredField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lease_id", models.BooleanField(default=True)),
                ("date_of_lease_date", models.BooleanField(default=True)),
                ("first_day_of_term_date", models.BooleanField(default=True)),
                ("last_day_of_term_date", models.BooleanField(default=False)),
                ("lease_expiration_date", models.BooleanField(default=True)),
                ("required_amount", models.BooleanField(default=False)),
                ("security_type_code", models.BooleanField(default=False)),
                ("tenant_id", models.BooleanField(default=True)),
                ("tenant_name", models.BooleanField(default=True)),
                ("is_company", models.BooleanField(default=True)),
                ("from_date", models.BooleanField(default=False)),
                ("option_to_date", models.BooleanField(default=False)),
                (
                    "option_type_break_purchase_renew",
                    models.BooleanField(default=False),
                ),
                (
                    "option_type_landlord_tenant_mutual",
                    models.BooleanField(default=False),
                ),
                ("term", models.BooleanField(default=False)),
                ("notice_term", models.BooleanField(default=False)),
                ("notice_term_date", models.BooleanField(default=False)),
                ("term_frequency", models.BooleanField(default=False)),
                ("fund_id", models.BooleanField(default=True)),
                ("property_id", models.BooleanField(default=True)),
                ("unit_id", models.BooleanField(default=True)),
                ("unit_type", models.BooleanField(default=True)),
                ("gross_area", models.BooleanField(default=True)),
                ("net_area", models.BooleanField(default=True)),
                ("vacant", models.BooleanField(default=True)),
                ("vacancy_note", models.BooleanField(default=False)),
                ("amount_rent", models.BooleanField(default=True)),
                ("amount_service_charge", models.BooleanField(default=False)),
                ("amount_others", models.BooleanField(default=False)),
                ("income_category_discount_amount", models.BooleanField(default=False)),
                ("charge_frequency", models.BooleanField(default=True)),
                ("vat_code", models.BooleanField(default=True)),
                ("vat_rate", models.BooleanField(default=True)),
                ("vat_amount", models.BooleanField(default=True)),
                ("start_payment_schedule", models.BooleanField(default=True)),
                ("end_payment_schedule", models.BooleanField(default=False)),
                ("currency_code", models.BooleanField(default=True)),
                ("index_series", models.BooleanField(default=False)),
                ("index_type", models.BooleanField(default=False)),
                ("start_date", models.BooleanField(default=False)),
                ("index_frequency", models.BooleanField(default=False)),
                ("index_date", models.BooleanField(default=False)),
                ("value", models.BooleanField(default=False)),
                ("value_sr2", models.BooleanField(default=False)),
                ("index_date_sr2", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lease_id",
                    models.CharField(
                        blank=True, default="lease_id ", max_length=250, null=True
                    ),
                ),
                (
                    "date_of_lease_date",
                    models.CharField(
                        blank=True,
                        default="date_of_lease_date",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "first_day_of_term_date",
                    models.CharField(
                        blank=True,
                        default="first_day_of_term_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "last_day_of_term_date",
                    models.CharField(
                        blank=True,
                        default="last_day_of_term_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "lease_expiration_date",
                    models.CharField(
                        blank=True,
                        default="lease_expiration_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "required_amount",
                    models.CharField(
                        blank=True, default="required_amount", max_length=250, null=True
                    ),
                ),
                (
                    "security_type_code",
                    models.CharField(
                        blank=True,
                        default="security_type_code",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True, default="tenant_id", max_length=250, null=True
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        blank=True, default="tenant_name", max_length=250, null=True
                    ),
                ),
                (
                    "is_company",
                    models.CharField(
                        blank=True, default="is_company", max_length=250, null=True
                    ),
                ),
                (
                    "from_date",
                    models.CharField(
                        blank=True, default="from_date", max_length=240, null=True
                    ),
                ),
                (
                    "to_date",
                    models.CharField(
                        blank=True, default="to_date", max_length=240, null=True
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        blank=True, default="type_code", max_length=250, null=True
                    ),
                ),
                (
                    "option_by_code",
                    models.CharField(
                        blank=True, default="option_by_code", max_length=250, null=True
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True, default="term", max_length=250, null=True
                    ),
                ),
                (
                    "notice_term",
                    models.CharField(
                        blank=True, default="notice_term", max_length=250, null=True
                    ),
                ),
                (
                    "notice_term_date",
                    models.CharField(
                        blank=True,
                        default="notice_term_date",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "term_frequency",
                    models.CharField(
                        blank=True, default="term_frequency", max_length=250, null=True
                    ),
                ),
                (
                    "fund_id",
                    models.CharField(
                        blank=True, default="fund_id", max_length=250, null=True
                    ),
                ),
                (
                    "property_id",
                    models.CharField(
                        blank=True, default="property_id", max_length=250, null=True
                    ),
                ),
                (
                    "unit_id",
                    models.CharField(
                        blank=True, default="unit_id", max_length=250, null=True
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        blank=True, default="unit_type", max_length=250, null=True
                    ),
                ),
                (
                    "gross_area",
                    models.CharField(
                        blank=True, default="gross_area", max_length=250, null=True
                    ),
                ),
                (
                    "net_area",
                    models.CharField(
                        blank=True, default="net_area", max_length=250, null=True
                    ),
                ),
                (
                    "vacant",
                    models.CharField(
                        blank=True, default="vacant", max_length=250, null=True
                    ),
                ),
                (
                    "vacancy_note",
                    models.CharField(
                        blank=True, default="vacancy_note", max_length=250, null=True
                    ),
                ),
                (
                    "amount_rent",
                    models.CharField(
                        blank=True, default="amount_rent", max_length=250, null=True
                    ),
                ),
                (
                    "amount_service_charge",
                    models.CharField(
                        blank=True,
                        default="amount_service_charge",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "amount_others",
                    models.CharField(
                        blank=True, default="amount_others", max_length=250, null=True
                    ),
                ),
                (
                    "amount_discount",
                    models.CharField(
                        blank=True, default="amount_discount", max_length=250, null=True
                    ),
                ),
                (
                    "charge_frequency",
                    models.CharField(
                        blank=True,
                        default="charge_frequency",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "vat_code",
                    models.CharField(
                        blank=True, default="vat_code", max_length=250, null=True
                    ),
                ),
                (
                    "vat_rate",
                    models.CharField(
                        blank=True, default="vat_rate", max_length=250, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.CharField(
                        blank=True, default="vat_amount", max_length=250, null=True
                    ),
                ),
                (
                    "start_payment_schedule",
                    models.CharField(
                        blank=True,
                        default="start_payment_schedule",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "end_payment_schedule",
                    models.CharField(
                        blank=True,
                        default="end_payment_schedule",
                        max_length=240,
                        null=True,
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True, default="currency_code", max_length=250, null=True
                    ),
                ),
                (
                    "index_series",
                    models.CharField(
                        blank=True, default="index_series", max_length=250, null=True
                    ),
                ),
                (
                    "index_type",
                    models.CharField(
                        blank=True, default="index_type", max_length=250, null=True
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True, default="start_date", max_length=240, null=True
                    ),
                ),
                (
                    "index_frequency",
                    models.CharField(
                        blank=True, default="index_frequency", max_length=250, null=True
                    ),
                ),
                (
                    "index_date",
                    models.CharField(
                        blank=True, default="index_date", max_length=240, null=True
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, default="value", max_length=250, null=True
                    ),
                ),
                (
                    "value_sr2",
                    models.CharField(
                        blank=True, default="value_sr2", max_length=240, null=True
                    ),
                ),
                (
                    "index_date_sr2",
                    models.CharField(
                        blank=True, default="index_date_sr2", max_length=250, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_structure",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
