# Generated by Django 4.2.1 on 2023-05-30 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datastructurerequiredfield",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
