# Generated by Django 4.2.1 on 2023-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datastructure",
            name="date_of_lease_date",
            field=models.CharField(
                blank=True, default="date_of_lease_date", max_length=250, null=True
            ),
        ),
    ]
