# Generated by Django 4.2.1 on 2023-11-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0003_remove_datastructure_type_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
