# Generated by Django 4.2.1 on 2023-06-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "structures",
            "0003_rename_rent_security_datastructurerequiredfield_required_amount_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="datastructurerequiredfield",
            old_name="income_category_rent_amount",
            new_name="amount_rent",
        ),
    ]
